author           = Linuxdirk
depends          = default,pooper
description      = The mods adds a hunger bar at the position of the breath bar and hides the bar if the breath bar becomes visible so the most important bar is shown without cluttering the UI too much.
name             = hunger_ng
optional_depends =
release          = 32055
title            = IA Hunger NG
