author           = Linuxdirk
depends          = default,beds,claycrafter,pooper
description      = haxx af
name             = hunger_ng
optional_depends =
release          = 32055
title            = IA Hunger NG
