author           = Linuxdirk
depends          = default,beds,pooper,peeer
#,drinks
description      = haxx af
name             = hunger_ng
optional_depends = airtanks, placeable_buckets
release          = 32055
title            = IA Hunger NG
